# Importing Libraries

In [2]:
pip install selenium

Collecting selenium
  Downloading selenium-4.23.1-py3-none-any.whl (9.4 MB)
     ---------------------------------------- 9.4/9.4 MB 1.2 MB/s eta 0:00:00
Collecting typing_extensions~=4.9
  Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Collecting websocket-client~=1.8
  Downloading websocket_client-1.8.0-py3-none-any.whl (58 kB)
     ---------------------------------------- 58.8/58.8 kB 1.0 MB/s eta 0:00:00
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\arnol\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\arnol\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Collecting trio~=0.17
  Downloading trio-0.26.2-py3-none-any.whl (475 kB)
     -------------------------------------- 476.0/476.0 kB 1.8 MB/s eta 0:00:00
Collecting outcome
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Collecting sniffio>=1.3.0
  Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting attrs>=23.2.0
  Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
     ---------------------------------------- 63.0/63.0 kB 1.1 MB/s eta 0:00:00
Collecting exceptiongroup
  Downloading exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
Requirement already satisfied: cffi>=1.14 in c:\users\arnol\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: sortedcontainers in c:\users\arnol\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\arnol\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Collecting wsproto>=0.14
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\arnol\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\arnol\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Collecting h11<1,>=0.9.0
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ---------------------------------------- 58.3/58.3 kB 3.0 MB/s eta 0:00:00
Installing collected packages: websocket-client, typing_extensions, sniffio, h11, exceptiongroup, attrs, wsproto, outcome, trio, trio-websocket, selenium
  Attempting uninstall: websocket-client
    Found existing installation: websocket-client 0.58.0
    Uninstalling websocket-client-0.58.0:
      Successfully uninstalled websocket-client-0.58.0
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.3.0
    Uninstalling typing_extensions-4.3.0:
      Successfully uninstalled typing_extensions-4.3.0
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.2.0
    Uninstalling sniffio-1.2.0:
      Successfully uninstalled sniffio-1.2.0
  Attempting uninstall: attrs
    Found existing installation: attrs 21.4.0
    Uninstalling attrs-21.4.0:
      Successfully uninstalled attrs-21.4.0
Successfully installed attrs-24.2.0 exceptiongroup-1.2.2 h11-0.14.0 outcome-1.3.0.post0 selenium-4.23.1 sniffio-1.3.1 trio-0.26.2 trio-websocket-0.11.1 typing_extensions-4.12.2 websocket-client-1.8.0 wsproto-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
import requests
from bs4 import BeautifulSoup as bs
import selenium
from selenium.webdriver.common.by import By
from selenium import webdriver
import pandas as pd

In [4]:
url = 'https://www.worldometers.info/coronavirus/'
html = requests.get(url).text
soup = bs(html, 'html.parser')

table = soup.find('table')
tr = table.find_all('tr')
print(tr[0])
print('\n')
print(tr[1])

<tr>
<th width="1%">#</th>
<th width="100">Country,<br>Other</br></th>
<th width="20">Total<br>Cases</br></th>
<th width="30">New<br>Cases</br></th>
<th width="30">Total<br>Deaths</br></th>
<th width="30">New<br>Deaths</br></th>
<th width="30">Total<br>Recovered</br></th>
<th width="30">New<br>Recovered</br></th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>


<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>131,889,132</td>
<td></td>
<td>1,695,941</td>
<td></td>
<td>127,665,129</td>
<td>+350</td>
<td>2,528,062</td>
<td>6,095</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>

In [5]:
cov_columns = [i.text for i in tr[0].find_all('th')]
cov_columns

['#',
 'Country,Other',
 'TotalCases',
 'NewCases',
 'TotalDeaths',
 'NewDeaths',
 'TotalRecovered',
 'NewRecovered',
 'ActiveCases',
 'Serious,Critical',
 'Tot\xa0Cases/1M pop',
 'Deaths/1M pop',
 'TotalTests',
 'Tests/\n1M pop\n',
 'Population',
 'Continent',
 '1 Caseevery X ppl',
 '1 Deathevery X ppl',
 '1 Testevery X ppl',
 'New Cases/1M pop',
 'New Deaths/1M pop',
 'Active Cases/1M pop']

In [6]:
cov_data = []
for rows in tr:
    values = [value.text for value in rows.find_all('td')]
    cov_data.append(values)

In [7]:
covid_df = pd.DataFrame(data = cov_data, columns = cov_columns)
covid_df.drop(list(covid_df.filter(regex = 'pop|ppl')), axis = 1, inplace = True)
covid_df

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotalTests,Population,Continent
0,None,None,None,None,None,None,None,None,None,None,None,None,None
1,,\nNorth America\n,"131,889,132",,"1,695,941",,"127,665,129",+350,"2,528,062","6,095",,,North America
2,,\nAsia\n,"221,500,265",,"1,553,662",,"205,673,091",,"14,273,512","14,733",,,Asia
3,,\nEurope\n,"253,406,198",,"2,101,824",,"248,754,104",+474,"2,550,270","4,453",,,Europe
4,,\nSouth America\n,"70,200,879",,"1,367,332",,"66,683,585",,"2,149,962","8,953",,,South America
...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,,Total:,"70,200,879",,"1,367,332",,"66,683,585",,"2,149,962","8,953",,,South America
244,,Total:,"14,895,771",,"33,015",,"14,752,388",,"110,368",31,,,Australia/Oceania
245,,Total:,"12,860,924",,"258,892",,"12,090,808",,"511,224",529,,,Africa
246,,Total:,721,,15,,706,,0,0,,,
247,,Total:,"704,753,890",0,"7,010,681",0,"675,619,811",+790,"22,123,398","34,794",,,All

In [8]:
covid_df.to_csv('CovidCases.csv', encoding='utf-8', index=False)

In [7]:
option = webdriver.ChromeOptions()
option.add_argument('headless')   # This option hides the browser

driver = webdriver.Chrome("C:\\Users\\asus1\\Downloads\\chromedriver.exe", options=option)
driver.get('https://ourworldindata.org/covid-vaccinations?country=OWID_WRL')
driver.implicitly_wait(10)

driver.implicitly_wait(10)
table = driver.find_element(By.XPATH, '/html/body/main/article/div[3]/div[2]/div/div/section[16]/div[3]/div/div/table')

vac_columns = []
for value in table.find_elements(By.XPATH, './/tr')[0].find_elements(By.XPATH, './/th'):
    vac_columns.append(value.text)

vac_data = []
for rows in table.find_elements(By.XPATH, './/tr'):
    values = [value.text for value in rows.find_elements(By.XPATH, './/td')]
    vac_data.append(values)
    
driver.close()

print(vac_columns)
print(vac_data[0:5])

C:\Users\asus1\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  after removing the cwd from sys.path.

['Location', 'Source', 'Last observation date', 'Vaccines']
[[], ['Afghanistan', 'World Health Organization', 'Jun. 30, 2022', 'CanSino, Covaxin, Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm/Beijing, Sinovac, Sputnik Light, Sputnik V'], ['Albania', 'World Health Organization', 'Jun. 26, 2022', 'Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, Sputnik V'], ['Algeria', 'World Health Organization', 'May. 29, 2022', 'Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac, Sputnik V'], ['Andorra', 'World Health Organization', 'Jun. 26, 2022', 'Moderna, Oxford/AstraZeneca, Pfizer/BioNTech']]

In [8]:
vaccine_df = df = pd.DataFrame(data = vac_data, columns = vac_columns)
vaccine_df

,Location,Source,Last observation date,Vaccines
0,None,None,None,None
1,Afghanistan,World Health Organization,"Jun. 30, 2022","CanSino, Covaxin, Johnson&Johnson, Moderna, Ox..."
2,Albania,World Health Organization,"Jun. 26, 2022","Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ..."
3,Algeria,World Health Organization,"May. 29, 2022","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac..."
4,Andorra,World Health Organization,"Jun. 26, 2022","Moderna, Oxford/AstraZeneca, Pfizer/BioNTech"
...,...,...,...,...
219,Wales,Government of the United Kingdom,"Jun. 22, 2022","Moderna, Oxford/AstraZeneca, Pfizer/BioNTech"
220,Wallis and Futuna,SPC Public Health Division,"May. 2, 2022",Moderna
221,Yemen,World Health Organization,"Jun. 19, 2022","CanSino, Covaxin, Johnson&Johnson, Moderna, Ox..."
222,Zambia,Government of Zambia,"Jun. 30, 2022","Johnson&Johnson, Oxford/AstraZeneca, Sinopharm..."
223,Zimbabwe,Ministry of Health,"Jun. 26, 2022","Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac..."

In [9]:
vaccine_df.to_csv('Vaccines.csv', encoding='utf-8', index=False)

In [10]:
option = webdriver.ChromeOptions()
option.add_argument('headless')   # This option hides the browser

driver = webdriver.Chrome("C:\\Users\\asus1\\Downloads\\chromedriver.exe", options=option)
driver.get('https://ourworldindata.org/covid-vaccinations?country=OWID_WRL')
driver.implicitly_wait(10)

element = driver.find_element(By.XPATH,'/html/body/main/article/div[3]/div[2]/div/div/section[1]/figure/div/div[3]/div/div/div[2]/nav/ul/li[2]/a')
driver.execute_script("arguments[0].click();", element)

driver.execute_script(
    'return arguments[0].scrollIntoView();', driver.find_element(
        By.XPATH, '/html/body/main/article/div[3]/div[2]/div/div/section[1]/figure/div/div[3]/div'
    )
)

driver.implicitly_wait(10)
element = driver.find_element(By.XPATH,'/html/body/main/article/div[3]/div[2]/div/div/section[1]/figure/div/form/div[3]/div[2]/label/input')
driver.execute_script("arguments[0].click();", element)
table = driver.find_element(By.XPATH, '/html/body/main/article/div[3]/div[2]/div/div/section[1]/figure/div/div[3]/div/div[1]/div/table')

vaccinated_columns = table.find_elements(By.XPATH, './/tr')[0].text.split('\n')

vaccinated_data = []
for rows in table.find_elements(By.XPATH, './/tr'):
    values = [value.text for value in rows.find_elements(By.XPATH, './/td')]
    vaccinated_data.append(values)
        
driver.close()

print(vaccinated_columns)
print(vaccinated_data[0:5])

C:\Users\asus1\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  after removing the cwd from sys.path.

['Country', 'People with a complete initial protocol', 'Jul 1, 2022', 'People only partly vaccinated', 'Jul 1, 2022']
[[], ['Afghanistan', 'Jun 30, 2022 5,064,430', 'Jun 30, 2022 648,854'], ['Africa', '256,959,096', '70,960,626'], ['Albania', 'Jun 26, 2022 1,248,781', 'Jun 26, 2022 77,764'], ['Algeria', '', '']]

In [11]:
vaccinated_columns
vaccinated_columns.pop(2)
vaccinated_columns.pop(3)

vaccinated_df = pd.DataFrame(data = vaccinated_data, columns = vaccinated_columns)
vaccinated_df

,Country,People with a complete initial protocol,People only partly vaccinated
0,None,None,None
1,Afghanistan,"Jun 30, 2022 5,064,430","Jun 30, 2022 648,854"
2,Africa,"256,959,096","70,960,626"
3,Albania,"Jun 26, 2022 1,248,781","Jun 26, 2022 77,764"
4,Algeria,,
...,...,...,...
226,Wallis and Futuna,,
227,World,"4,801,826,705","432,429,972"
228,Yemen,"Jun 19, 2022 446,120","Jun 19, 2022 251,836"
229,Zambia,,
230,Zimbabwe,"Jun 26, 2022 4,624,556","Jun 26, 2022 1,689,568"

In [12]:
vaccinated_df.to_csv('Vaccinated.csv', encoding='utf-8', index=False)